name = "Folly"
uuid = "765c1465-b1aa-46ee-b6b0-911d12e3f8a9"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[compat]
julia = 1.3
KernelAbstractions = 0.3
